# Generated by Django 4.2.3 on 2023-07-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_shoppingcart_products'),
        ('orders', '0003_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopping_carts',
            field=models.ManyToManyField(to='shoppingcart.shoppingcart'),
        ),
    ]
