# Generated by Django 4.2.3 on 2023-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('shipping_carrier', models.CharField(max_length=50)),
                ('tracking_status', models.CharField(max_length=100)),
            ],
        ),
    ]
