# Generated by Django 4.2.3 on 2023-07-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shopping_carts'),
        ('shipping', '0003_alter_shipping_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
