# Generated by Django 4.2.3 on 2023-08-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
